title: "Welcome Future Innovators"
description: JHUAPL Future Innovator Event
remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: true
collections:
  women:
    output: true
