title: "APL STEM: Future Innovators!"
description: STEM Workshop for APL Future Innovators
remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: true
collections:
  women:
    output: true
